# Etapa 1: Construcción
FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npm run build

# Etapa 2: Producción
FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production --legacy-peer-deps

# Copiar el build compilado desde la etapa anterior
COPY --from=builder /app/dist ./dist

EXPOSE 3000

ENV PORT=3000

CMD ["node", "dist/main"]
